In [1]:
%pylab inline

/home/ciuffreda/anaconda3/lib/python3.6/site-packages/matplotlib/font_manager.py:280: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  'Matplotlib is building the font cache using fc-list. '


Populating the interactive namespace from numpy and matplotlib


In [3]:
dir()

['ALLOW_THREADS',
 'Annotation',
 'Arrow',
 'Artist',
 'AutoLocator',
 'Axes',
 'BUFSIZE',
 'Button',
 'CLIP',
 'Circle',
 'ComplexWarning',
 'DAILY',
 'DataSource',
 'DateFormatter',
 'DateLocator',
 'DayLocator',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'FR',
 'False_',
 'Figure',
 'FigureCanvasBase',
 'FixedFormatter',
 'FixedLocator',
 'FormatStrFormatter',
 'Formatter',
 'FuncFormatter',
 'GridSpec',
 'HOURLY',
 'HourLocator',
 'In',
 'IndexDateFormatter',
 'IndexLocator',
 'Inf',
 'Infinity',
 'LinAlgError',
 'Line2D',
 'LinearLocator',
 'Locator',
 'LogFormatter',
 'LogFormatterExponent',
 'LogFormatterMathtext',
 'LogLocator',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MINUTELY',
 'MO',
 'MONTHLY',
 'MachAr',
 'MaxNLocator',
 'MinuteLocator',
 'ModuleDeprecationWarning',
 'MonthLocator',
 'MultipleLocator',
 'NAN

In [4]:
ndarray?

In [5]:
#ndarray is a tensor!

In [6]:
#examples

In [7]:
zeros?

In [8]:
a=zeros((3,4,5))

In [9]:
a

array([[[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]]])

In [16]:
b=arange(60)

In [17]:
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50 51 52 53 54 55 56 57 58 59]


In [18]:
type(arange)

builtin_function_or_method

In [19]:
b.shape

(60,)

In [20]:
c=b.reshape((3,4,5))

In [21]:
print(c)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


In [23]:
d=b.reshape((3,4,5),F)

NameError: name 'F' is not defined

In [24]:
reshape?

In [25]:
d=b.reshape((3,4,5),order='F')

In [26]:
print(d)

[[[ 0 12 24 36 48]
  [ 3 15 27 39 51]
  [ 6 18 30 42 54]
  [ 9 21 33 45 57]]

 [[ 1 13 25 37 49]
  [ 4 16 28 40 52]
  [ 7 19 31 43 55]
  [10 22 34 46 58]]

 [[ 2 14 26 38 50]
  [ 5 17 29 41 53]
  [ 8 20 32 44 56]
  [11 23 35 47 59]]]


In [27]:
o=ones((3,4,5))

In [28]:
o+c

array([[[  1.,   2.,   3.,   4.,   5.],
        [  6.,   7.,   8.,   9.,  10.],
        [ 11.,  12.,  13.,  14.,  15.],
        [ 16.,  17.,  18.,  19.,  20.]],

       [[ 21.,  22.,  23.,  24.,  25.],
        [ 26.,  27.,  28.,  29.,  30.],
        [ 31.,  32.,  33.,  34.,  35.],
        [ 36.,  37.,  38.,  39.,  40.]],

       [[ 41.,  42.,  43.,  44.,  45.],
        [ 46.,  47.,  48.,  49.,  50.],
        [ 51.,  52.,  53.,  54.,  55.],
        [ 56.,  57.,  58.,  59.,  60.]]])

In [30]:
c*c

array([[[   0,    1,    4,    9,   16],
        [  25,   36,   49,   64,   81],
        [ 100,  121,  144,  169,  196],
        [ 225,  256,  289,  324,  361]],

       [[ 400,  441,  484,  529,  576],
        [ 625,  676,  729,  784,  841],
        [ 900,  961, 1024, 1089, 1156],
        [1225, 1296, 1369, 1444, 1521]],

       [[1600, 1681, 1764, 1849, 1936],
        [2025, 2116, 2209, 2304, 2401],
        [2500, 2601, 2704, 2809, 2916],
        [3025, 3136, 3249, 3364, 3481]]])

In [31]:
(c+1)*(c+1)

array([[[   1,    4,    9,   16,   25],
        [  36,   49,   64,   81,  100],
        [ 121,  144,  169,  196,  225],
        [ 256,  289,  324,  361,  400]],

       [[ 441,  484,  529,  576,  625],
        [ 676,  729,  784,  841,  900],
        [ 961, 1024, 1089, 1156, 1225],
        [1296, 1369, 1444, 1521, 1600]],

       [[1681, 1764, 1849, 1936, 2025],
        [2116, 2209, 2304, 2401, 2500],
        [2601, 2704, 2809, 2916, 3025],
        [3136, 3249, 3364, 3481, 3600]]])